server:
  port: 8000
qiniu:
  miniapp:
    secret-key: k0qlwdpAUz9YGZquTVFsuihTmxzkSEuzZiwKx7dd
    access-key: CLyTaquEijPEA9ikwsVybg1Iv26b03jA1rSa1b5d
    bucket: lbnbhl

wx:
  miniapp:
#    走孟凡
#    appid: wx72bfaf034d30e604
#    secret: 70fa304eb593d797a4b509858f3357bd
     appid: wxa7324303aa0a8917
     secret: d5da157e742149e31bb6a448c0255a2f

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wechat?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: wwl04212430
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    #设置文件上传上限
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  thymeleaf:
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
    mode: HTML # 用非严格的 HTML
    #编码 可不用配置
    encoding: UTF-8
    #内容类别,可不用配置
    servlet:
      content-type: text/html


#spring:
#  #配置数据源
#  datasource:
#    #配置数据源类型
#    type: com.zaxxer.hikari.HikariDataSource
#    #配置数据库连接属性
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/wechat?characterEncoding=utf-8&serverTimezone=GMT%2B8&userSSL=false
#    username: root
#    password: root
#    #url: jdbc:mysql://r2czkq1vewxat78mnyg60oisurj5h4dp.mysql.qingcloud.link:3306/ssg_zhxy_db?characterEncoding=utf-8&serverTimezone=GMT%2B8&userSSL=false
#    #username: shangguigu
#    #password: shangguigu@QY123
#    #mybatis-plus内置连接池
#    hikari:
#      connection-test-query: SELECT 1
#      connection-timeout: 60000
#      idle-timeout: 500000
#      max-lifetime: 540000
#      maximum-pool-size: 12
#      minimum-idle: 10
#      pool-name: GuliHikariPool
#  #thymeleaf:
#    #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
#    #mode: HTML5
#    #编码 可不用配置
#    #encoding: UTF-8
#    #开发配置为false,避免修改模板还要重启服务器
#    #cache: false
#    #配置模板路径，默认是templates，可以不用配置
#    #prefix: classpath:/static/
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#mybatis-plus:
#  configuration:
#    #添加日志支持
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath*:/mapper/**/*.xml
#qiniu:
#  miniapp:
#    access-key: CLyTaquEijPEA9ikwsVybg1Iv26b03jA1rSa1b5d
#    secret-key: k0qlwdpAUz9YGZquTVFsuihTmxzkSEuzZiwKx7dd
#    bucket: lbnbhl

